### ISSUE TITLE
1/10 TODO

### ISSUE THREAD

**Issue by yoopark** [lev-Zero/lastpong#164]
- [x] 방 제목/비밀번호 등 사용자 input에 특수문자 및 공백 불가능하게 처리
- [x] owner 방 정보 변경하는 모달 완료
- [ ] DM 간헐적으로 안 보내지는 현상 원인 파악하기 (FE인지 BE인지)
- [x] /game/options에 아바타 넣기
- [x] /watch 제작하기

**Comment by yoopark** [comment]
#150 으로 이전
