### ISSUE TITLE
12/26 TODO

### ISSUE THREAD

**Issue by yoopark** [lev-Zero/lastpong#43]
- [x] /auth/login을 /로 변경하고, 로그인과 비로그인 상태에 따라 다르게 라우팅
- [x] 로그인했을 때 JWT 토큰 쿠키에 저장되도록 하기
- [x] zustand로 Userprops 상태관리할 수 있도록 하기 (각 프로퍼티별로 떼서 get)
- [x] fetch utils 만들기
- [x] zustand 파일 bestPractice 참고해서 만들기
- [ ] /auth/basic 연동하기
- [ ] 이미지 업로드 방법 구상
- [x] 다른 컴퓨터에서 내 localhost 접속할 수 있는지 방법 알기

---

시간 남으면

- [ ] DM 모달창 뷰 만들기
- [x] 채팅창 뷰 만들기
- [x] friend 더미데이터 만들고 연동해보기

**Comment by lev-Zero** [comment]
오늘도 열심히 해보겠습니당
