### ISSUE TITLE
12/28 TODO

### ISSUE THREAD

**Issue by yoopark** [lev-Zero/lastpong#55]
- [ ] socket.io 공부
- [ ] zustand @lev-Zero 님과 함께 잘 연동하기
- [ ] socket.io 채팅 기능을 next.js - typescript 프로젝트에 맞게 임포트해보기

**Comment by yoopark** [comment]
Projects/TODO로 이전
