### ISSUE TITLE
1/2 TODO

### ISSUE THREAD

**Issue by yoopark** [lev-Zero/lastpong#97]
휴대폰으로 작성중이라 Project가 아닌 Issue에 임시로 작성합니다 ㅎㅎ

- [ ] router.query 리팩토링
- [ ] chat socket /chat 페이지가 아닌 /에서 처음 만들고, 다른 페이지도 없으면 새로 만들도록 전역에 로직 추가
- [ ] chat 주고받는 로직 짜기
- [ ] socket 관련 깔끔하게 정리 (정리 안하면 분명 꼬일듯)
